services:
  app:
    image: finhabit-app:local
    container_name: finhabit-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - finhabit-mysql
    restart: unless-stopped

  finhabit-mysql:
    image: mysql:8.0.43
    container_name: finhabit-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: finhabit_root
      MYSQL_DATABASE: finhabit_db
      MYSQL_USER: teamF
      MYSQL_PASSWORD: finhabit_pw
      TZ: Asia/Seoul
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3307:3306"
    volumes:
      - ./_vol/mysql:/var/lib/mysql