spring:
  datasource:
    url: jdbc:mysql://localhost:3307/finhabit_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8 # docker-compose.dev.yml에서 포트번호 3307:3306으로 바꾸면서 여기도 같이 3307로 바꿈
    username: teamF
    password: finhabit_pw
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
server.port: 8080